### ISSUE TITLE
is there a way to get barcode format ?

### ISSUE THREAD

**Issue by kamedan** [dorumrr/npmjs-cordova-honeywell-scanner-simplified#3]
i used a zebra device before and they use intent to provide barcode type and data in the same object.
i don't know if this possible in this case.

**Comment by dorumrr** [comment]
In my opinion, that would be beyond the scope of the package (-simplified), especially being a piece of information that must be looked up after a scan took place. I will, however, see if I can implement a lightweight solution to this.
