### ISSUE TITLE
EAN13 with check digit and Add-on 5

### ISSUE THREAD

**Issue by sajt** [dorumrr/npmjs-cordova-honeywell-scanner-simplified#5]
I writing a Quasar app to my Honeywell EDA50-011 with 7.1.1 android.

I am using the following code:
```
window.plugins.honeywell.listen(function (data) {
        console.log(data)
        that.barCode.eanl = data.substring(0, 13)
        that.barCode.eanr = data.substring(13, 18)
      }, function (error) {
        console.log('Error occured: ' + error)
      })
```
When I test it with a EAN13 barcode with 5 digit add-on in the ```data``` there is only 12 digit.

In the settongs there is everything is ok and It was worked a while I got all digit, but something changed, and now not working perfectly.

What is the problem?

**Comment by R-Stefano** [comment]
Hi sajt,

I think I have the same problem. 
EAN barcodes: both 8 and 13 once scanned return 7 and 12 digits respectively.

How did you solve it?

**Comment by gabrielformiga** [comment]
I also had this problem, I was working on a setConfig for the plugin so we could customize some flags, but I didn't have time for it, so I hardcoded it on plugin initialization:
https://github.com/gabrielformiga/npmjs-cordova-honeywell-scanner-simplified/commit/7612c56a9d2c10b4d74118502de58e06e17e2b0b

**Comment by R-Stefano** [comment]
I solved by changing plugin and implementing some change to the .java code. Check it out
https://github.com/R-Stefano/cordova-honeywell-scanner

**Comment by dorumrr** [comment]
> I solved by changing plugin and implementing some change to the .java code. Check it out https://github.com/R-Stefano/cordova-honeywell-scanner

Nice one! You can always create a PR if you want your contributions to be added to the package.
