### ISSUE TITLE
Scanning with the buttons does not update the view

### ISSUE THREAD

**Issue by andrespadron98** [dorumrr/npmjs-cordova-honeywell-scanner-simplified#8]
Hi, I am testing its functionality and when I use the scanPressed and scanReleased functions with a button in the app it works perfect for me, but when scanning with the buttons of the Honeywell EDA51 it gets the code but does not update the view. What could it be?

**Comment by pierresh** [comment]
If you are using Ionic, I think you need to do a wrapper with Ionic native. See these links:

https://github.com/ionic-team/ionic-native/issues/912#issuecomment-273226642

https://github.com/danielsogl/awesome-cordova-plugins/blob/master/DEVELOPER.md#creating-plugin-wrappers
